### ISSUE TITLE
feat: statistics

### ISSUE THREAD

**Issue by Lichtsignaal** [cookiemumbles/justmytoots.com#26]
Hi and thanks for making this wonderful elegant piece of software! I was playing around with it and before this I was building some powershell/bash things with the mastodon API to create statistics of posts. 

I wonder if it would be nice to introduce that since Mastodon, as far as I know, doesn't support that. I think the filtering on hashtags would be needed for that in orde to create statistics for certain type of posts. For myself for example I'd like statistics on al my "#photo" tagged items.

I's love to contribute a bit but am not very proficient at JS, but I will try and figure things out on a local instance so I might contribute in the future. Thanks again!

**Comment by cookiemumbles** [comment]
Hey thanks for the positive feedback!

I don't think I quite understand what you mean with "statistics" in this context though. The page is meant to showcase your content to people visiting your profile, so I don't feel like real toot statistics (like you can see for you own tweets on twitter for example) are the right place to display on here.
If I read your request another way however, you could also mean you would like special _filtering_ of toots. Well then I can tell you that I already have some ideas about that in this feature: #19 
I could expand that one to include hashtags I guess, even though freetext input might be a bit more challenging to combine with my current ideas...

**Comment by Lichtsignaal** [comment]
Well, yeah, the statistics are meant in a way comparable to Twitter analytics, but on the other hand you might be right, maybe not the right place for that. Filtering would be nice in any case. I'm not sure I can filter my toots on mastodon with just hashtags and my own posts, so I would definitely upvote a feature like that, be it in this nice gem or on mastodon itself.

Freetext could be a thing, but I'm not sure that is in the spirit of the original design. Anyway, if I could showcase my pictures tagged with a hashtag, that would be neat!

**Comment by cookiemumbles** [comment]
Yes I think the statistics could be nice, but should be a separate thing from the justmytoots page.
But I have to admit I'm not sure this information even is available through the mastodon api in the first place. I couldn't find it with a quick glance but it might be someplace else.

About the hashtags though, I've included it in the list on #19 but if you have posts that use a hashtag anyway you could alternatively use a custom "private" hashtag. You could for example add a `#LichtSignaalToots` hashtag to your posts, and if people click the hashtag it displays all your posts where you've added the hashtag. @sonictyrant@mstdn.social does this with his jokes and a `#iuas` hashtag for example: https://ohai.social/@sonictyrant@mstdn.social/109598354866268335

I'm closing this issue as I've added the hashtag thing to the other ticket. Thanks though!
