### ISSUE TITLE
issue: The requested resource not found

### ISSUE THREAD

**Issue by Lichtsignaal** [cookiemumbles/justmytoots.com#27]
For my local instance I get the following error:

The requested resource /@lichtsignaal@mastodon.nl was not found on this server.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/120838425/209800030-b2469283-a997-42b2-89c8-44a346785662.png">

I think this is something with the PHP settings or Apache rewrite or something. Can you confirm? I'd like to see if I can start adding features to this very handy piece of software. Thanks!

**Comment by cookiemumbles** [comment]
It kind of looks like your url is broken and you're ending up on your localhost webserver if I'm not mistaken.
It seems to work like this: https://justmytoots.com/@lichtsignaal@mastodon.nl

**Comment by Lichtsignaal** [comment]
Ow yeah, sorry, I cloned the repo of course and started a server locally on a Pi of mine. I even tried with the -t option to specify the root directory, but this error keep creeping up. When I add a phpinfo() in a file it runs like a charm and also reports the correct root directory. I'm pretty sure I'm missing something, probably to do with URL parsing, but it's been a while since I ran PHP.

Could it be a dependancy missing or something with the ARM core of the Pi? I doubt it though, but mentioning it nonetheless. I'm trying to setup a local version to see if I can contribute a bit of code maybe.

**Comment by cookiemumbles** [comment]
Ah okay I understand. I simply run the [startServer.sh](https://github.com/cookiemumbles/justmytoots.com/blob/main/startServer.sh) script on my local machine to test, but the url rewrite stuff is in the [.htaccess file](https://github.com/cookiemumbles/justmytoots.com/blob/main/public/.htaccess). I haven't set up the .httacces rules for myself locally either, and just use the fallback argument syntax instead. That would look like this for example: http://127.0.0.1?acct=@lichtsignaal@mastodon.nl

**Comment by cookiemumbles** [comment]
I’m going to close the issue for now. I’ll add a read me with a description of how to test locally. Thanks for bringing this to my attention
